---
title: |
  Documentos Reprodutíveis em R Markdown 
subtitle: |
  como Forma de Autodocumentação do
  Processo de Produção de Conteúdo
author: "Marcelo Ventura Freire"
date: "30/11/2019"
output: 
  ioslides_presentation: 
    incremental: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## O que queremos fazer?

Apresentar uma forma de o produtor de conteúdo conseguir escalar a sua capacidade de produção, sem perda de precisão ou acurácia e com ganho de segurança.


## Outline

Nesta palestra, vamos apresentar 

- um conjunto de princípios, boas práticas e recursos computacionais 
- alguns mais e outros menos manjados quando considerados separadamente, mas que 
- não são usados conjuntamente com a frequência e a orientação que mereciam
- com isso, esta palestra pode ficar trivial para alguns contudo útil para outros
    - meus pedidos de perdão antecipados para o primeiro grupo
    

## Quais princípios?

Princípios que consideraremos

- programação literária (*literate programming*), 
- reprodutibilidade de pesquisa (*reproducible research*)

## Quais boas práticas?

Boas práticas de programação que consideraremos

- "código é documentação"
- "use sistema de controle de versionamento"
- "confie à programação os processos repetitivos"
- "reaproveite código que funciona"

## Quais ferramentas de computação?

Ferramentas que utilizaremos para ilustrar uma aplicação *aqui nesta apresentação*

- a linguagem de programação *R*
- a linguagem de marcação *Markdown* 
- o formato de arquivo e interface *R Markdown*
- o ambiente de desenvolvimento integrado *RStudio*
- o sistema de interface programável de aplicativo *API*
- os sistemas *G Suite* e JupiterWeb acessíveis através de sistema de API


----

**Ferramentas que também poderíamos considerar pelo mesmo custo mental se você já as dominar, mas que não daria tempo nem espaço de abordarmos porque já fomos insanamente ambiciosos de enfiar um monte de coisas na apresentação**

Por questão de brevidade, não vamos usar nesta apresentação, mas poderíamos ter usado também 

- as linguagens de programação *Python* e *SQL*
    - junto com o *Python*, vem quaisquer programas com interface via biblioteca *Python*
- o sistema de preparação de documentos *LaTeX*
- o pacote *Shiny* para montar web apps e dashboards
- outras fontes de dados acessíveis/raspáveis através de sistema de API, tais como o Facebook, Twitter, Instagram, Telegram, WhatsApp etc.


## Abordagem "tradicional"

- geração das diferentes partes do conteúdo em softwares diferentes
    - texto
    - imagens
    - tabelas
    - etc.
- junção manual através do recurso de cópia e colagem do editor de texto
    - geralmente MS-Word ou Google Docs


## Abordagem "tradicional"

- vantagens
    - rápido de aprender
    - rápido de fazer
- desvantagens
    - perda da origem das partes do texto
    - perda do como as partes foram feitas
    - se uma das imagens ou tabelas não for mais reconhecida internamente
        - pelo MS-Word e não houver uma cópia em disco junto com o .doc/.docx 
        - para o Google Docs e não houver uma cópia no Google Drive
        - então já era: o grande X vermelho

---

- alguns princípio de programação que podem ajudar
    - código é documentação
        - o código que gerou a imagem ou tabela *já é* documentação: de onde
          vieram os dados, como foi calculado, quais opções de visualização 
          foram usadas no gráfico ou tabela
        - o código que buscou a informação online *já é* documentação: de onde 
          os dados foram raspados, como foi processado, quais opções de
          visualização foram usadas
    - use sistema de controle de versionamento
        - e.g., git
        - permite rastrear a versão documento
            - sabe o "putz, não podiam ter jogado fora aquele gráfico" e o "é,
              ninguém mais consegue achar o arquivo de imagem e nem cópia da
              versão anterior"?
            - pois é, isso não acontece com um sistema de controle de versão
            - é possível dar um *rollback* pra qualquer versão de interesse
        - bônus: permite redação colaborativa do documento
            - Google Docs também consegue
    - confie à programação os processos repetitivos
        - não use o loop copie-cole-altere-copie-cole-altere-...
            - você **vai** errar em algum ponto
            - se você precisar refazer, vai errar em *outro* ponto, de modo que
              nunca vai ficar igual à primeira versão
        - use um chunk que obtenha, processe e formate os dados
    - reaproveite código que funciona
        - o chunk que funciona em um documento pode servir de início e ser
          adaptado para uma finalidade próxima em outro documento




- vantagens
    - R Makrdown consegue gerar saídas em
        - .pdf (texto ou slides)
        - .html (texto, slides ou dashboard)
        - .ppt/.pptx
        - .doc/.docx


- dados na internet
    - páginas estáticas
    - páginas dinâmicas
        - geradas por API
            - url de uma página gerada por API
            
            
pegar a imagem de:
- <https://uspdigital.usp.br/jupiterweb/jupDisciplinaBusca?tipo=D>

analisar a sintaxe de
- <https://uspdigital.usp.br/jupiterweb/obterDisciplina?nomdis=&sgldis=ACH0021>
- <https://uspdigital.usp.br/jupiterweb/listarGradeCurricular?codcg=86&codcur=86450&codhab=202&tipo=N>





acessíveis via API

- técnicas de raspagem de dados
    - uso de API pra pedir e obter dados em forma JSON ou XML
        - packages 
- interface com sistemas cloud
    - até tem o sistema de API, mas alguns packages encapsulam a sintaxe,pra 
      facilitar a vida
- reaproveitamento de código em outras circunstâncias
  



- reproducible research
- reproducible documents
- <https://kbroman.org/datacarpentry_R_2018-06-04/04-rmarkdown.html>
- litterate programming
- <https://andrewbtran.github.io/NICAR/2017/reproducibility-rmarkdown/rmarkdown.html>

- programação literária 
  ([*literate programming*](https://en.wikipedia.org/wiki/Literate_programming);
  mistura de texto e código), 
- reprodutibilidade de pesquisa 
  ([*reproducible research*](https://en.wikipedia.org/wiki/Reproducibility#Reproducible_research); 


- programação literária (*literate programming*; mistura de texto e código), 
- reprodutibilidade de pesquisa 
  (*reproducible research*; não redija o documento, mas sim o meta-documento 
  que gerará o documento)



